### ISSUE TITLE
Setup Docker

### ISSUE THREAD

**Issue by loziniak** [exercism/red-test-runner#2]
Add required Docker files. As proposed in #1 .

**Comment by loziniak** [comment]
>     What would you need from me? Probably a script to install Red?
> Yes. The script should preferrably work on either Alpine or Ubuntu.

**Comment by loziniak** [comment]
I'll try to use this: https://github.com/exercism/generic-test-runner , just found it :-)

**Comment by ErikSchierboom** [comment]
Excellent!

**Comment by ErikSchierboom** [comment]
I have a lot of experience using the generic test runner, so let me know if you need any help.

**Comment by loziniak** [comment]
Hmm I thought I was clear enough on https://github.com/exercism/red-test-runner/pull/1#issuecomment-814095247 . And since I had no feedback for almost a month, I thought I'm on my own. Now I'm a little confused. Anyway, [I managed to create Dockerfile](https://github.com/exercism/red-test-runner/pull/7) which allows to run Red in container. Can you make it form here?

Used also these as a guideline:
https://github.com/eranws/red-docker
https://github.com/dander/docker-red

**Comment by ErikSchierboom** [comment]
@loziniak Sorry, but it has been extremely busy on my end. I'll try and work on it next week probably.

**Comment by loziniak** [comment]
Sure, that was my first thought :-) Perhaps I could ask someone else? Do you know someone who would be suitable for the task from Exercism project? Or it's best to just ask on Slack?

**Comment by ErikSchierboom** [comment]
No worries, I'll give this a go and if I don't succeed I'll let you know.

**Comment by ErikSchierboom** [comment]
@loziniak I've worked on the test runner for a bit and left some comments.
