### ISSUE TITLE
Show all test results on failure

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/red-test-runner#49]
In the case of a failing test case, the other test cases' results are not shown.

Compare the C# and the Red test runner:

![image](https://user-images.githubusercontent.com/135246/185361084-666fa758-5469-4a0d-84e9-37835324f8ab.png)

![image (1)](https://user-images.githubusercontent.com/135246/185361073-8c555a46-e90f-4e9d-ad0f-d411611e54f0.png)

**Comment by loziniak** [comment]
@ErikSchierboom does test-runner deploy automatically? It's strange, because now I can see all test results in web editor, but test code is still not updated (`solution = "Hello, World!"` instead of `[expect "Hello, World!" [hello]]`

**Comment by ErikSchierboom** [comment]
@loziniak Yes it deploys automatically: https://github.com/exercism/red-test-runner/actions/runs/3726143265/jobs/6319393506

I've looked into this, and the reason the output is not what you expect is that there is a small bug in the `results.json` data. This is an example of a test's data in the `results.json` file:

```json
{
  "name": "no name given",
  "status": "pass",
  "message": "✓",
  "output": "",
  "test_code": "solution = \"One for you, one for me.\""
}
```

The problem is that the `message` property is not empty, but it should be omitted (or `null`) when the tests has a status of `pass`. Quoting the [test runner interface docs](https://exercism.org/docs/building/tooling/test-runners/interface#h-message-1):

> The per-test message key is used to return the results of a test with a status of `fail` or `error`.
> [...]
> If there is no test failure message or error message, either set the value to `null` or omit the key entirely.

The solution is thus to output `null` for the `message` key (or omit it entirely) if the `status` is `pass`.

Side note: the `output` property should also be `null` if there is no user output that is captured
