### ISSUE TITLE
Test runner image fails to build

### ISSUE THREAD

**Issue by BNAndras** [exercism/red-test-runner#62]
CI is broken per https://github.com/exercism/red-test-runner/actions/runs/7866754467 and https://github.com/exercism/red-test-runner/actions/runs/7866754506. If I bump the base image to ubuntu:jammy, running `./bin/run-tests-in-docker.sh` results in

```
** Syntax Error: (line 21) invalid construction spec at 
*** Where: transcode
*** Near : load script
*** Stack: load
```

I'll have some time later in the week to investigate further.

**Comment by loziniak** [comment]
Looks like two separate problems. I updated the code: exercism/red#148, #64 , but in `red-test-runner` there is a problem with _Ubuntu Kinetic_, and in `exercism/red` there is a problem with `red-test-runner`, which is not updated and treats updated syntax the old way.
